### ISSUE TITLE
Question regarding the intialization vector

### ISSUE THREAD

**Issue by sean-buchanan** [SimonCropp/Newtonsoft.Json.Encryption#6]
It seems to be from my reading of symmetric algorithms that the best practice is to use a different IV with each message. It seems many people just concatenate the IV with the encrypted data. Then to decrypt you just read the IV out of the first part of the encrypted data. From the sample code, it's not apparent whether the framework supports something like that. Any suggestions on how to accomplish that using this framework? Would I have to transport the IV separately along with the class instance I encrypted?

**Comment by SimonCropp** [comment]
sorry for the delay, for some reason i was not subscribed to my own repo :(

> from my reading of symmetric algorithms that the best practice is to use a different IV with each message. 

yes that is my understanding as well

When you encrypt you provide a new `SymmetricAlgorithm`
https://github.com/SimonCropp/Newtonsoft.Json.Encryption#serialization
the [IV](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.symmetricalgorithm.iv?view=netframework-4.7.2) of that instance is random and is used for encryption. 

The at decrypt https://github.com/SimonCropp/Newtonsoft.Json.Encryption#deserialization you need that IV. How you transfer that is up to you, but yes it can be transferred with the data

When using the Rebus.Newtonsoft.Encryption or NServiceBus.Newtonsoft.Encryption the IV is passed in the message headers

The Newtonsoft.Json.Encryption package has no default way of passing the IV. Happy to consider a PR if you want to add that functionality

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
